# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Data_&_Rocks
email: kylehiroyasu@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  My name is Kyle Hiroyasu, I'm interested in data science, stats, and data viz.
  Feel free to contact me!

baseurl: "" # the subpath of your site, e.g. /blog
url: "http://yourdomain.com" # the base hostname & protocol for your site
twitter_username: hiroyasu_kyle
github_username:  kylehiroyasu

# Build settings
markdown: kramdown
